import java.sql.*;
import Project.ConnectionProvider;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bhadoriya
 */
public class addNewQuestion extends javax.swing.JFrame {

    /**
     * Creates new form addNewQuestion
     */
     String topic="";
     int topicId =1;
    public addNewQuestion() {
        initComponents();
        try{
            Connection con=ConnectionProvider.getCon();
            if(con == null){
                System.out.println("connection not created");
                 System.exit(0);
            }
            Statement st = con.createStatement();
            ResultSet  rs = st.executeQuery("SELECT count(*) FROM Question");
                int id = 1;
                if(rs.next()){
                    id = rs.getInt(1);
                }
                String str = String.valueOf(id);
                Id.setText(str);
        }
        catch(Exception e){
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf , e);
        }
    }
    private void addNewTopic(){
         try{
            Connection con=ConnectionProvider.getCon();
            Statement s = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = s.executeQuery("Select count(*) from quiztopic");
            if(rs.first()){
               topicId = rs.getInt(1)+1;
            }
            PreparedStatement ps = con.prepareStatement("INSERT INTO QuizTopic VALUES(?,?)");
            ps.setInt(1,topicId);
            ps.setString(2, topic);
            ps.executeUpdate();
         }
         catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Close = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        QuestionName = new javax.swing.JTextField();
        Option1 = new javax.swing.JTextField();
        Option2 = new javax.swing.JTextField();
        Option3 = new javax.swing.JTextField();
        Option4 = new javax.swing.JTextField();
        Answer = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        TopicSearch = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TopicId = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add new question.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 32, 67, -1));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel2.setText("Add New Question");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 32, -1, 67));

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, 32, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 117, 1021, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Question ID :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        Id.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Id.setForeground(new java.awt.Color(255, 51, 51));
        Id.setText("00");
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Question :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 105, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("Option 1:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Option 2:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Option 3:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setText("Option 4:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setText("Answer :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 93, -1));

        QuestionName.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        QuestionName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionNameActionPerformed(evt);
            }
        });
        getContentPane().add(QuestionName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 689, -1));

        Option1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Option1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Option1ActionPerformed(evt);
            }
        });
        getContentPane().add(Option1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 689, -1));

        Option2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Option2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Option2ActionPerformed(evt);
            }
        });
        getContentPane().add(Option2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 689, -1));

        Option3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Option3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Option3ActionPerformed(evt);
            }
        });
        getContentPane().add(Option3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 689, -1));

        Option4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Option4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Option4ActionPerformed(evt);
            }
        });
        getContentPane().add(Option4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 689, -1));

        Answer.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerActionPerformed(evt);
            }
        });
        getContentPane().add(Answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 689, -1));

        save.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 500, -1, -1));

        Clear.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 500, -1, -1));

        Search.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        TopicSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TopicSearch.setForeground(new java.awt.Color(204, 204, 204));
        TopicSearch.setText("enter topic name");
        TopicSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TopicSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TopicSearchFocusLost(evt);
            }
        });
        TopicSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TopicSearchActionPerformed(evt);
            }
        });
        getContentPane().add(TopicSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 132, 200, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setText("Topic ID:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, -1, -1));

        TopicId.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        TopicId.setForeground(new java.awt.Color(255, 0, 0));
        TopicId.setText("00");
        getContentPane().add(TopicId, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 130, 43, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages background admin.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Option1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Option1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Option1ActionPerformed

    private void Option2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Option2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Option2ActionPerformed

    private void Option3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Option3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Option3ActionPerformed

    private void Option4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Option4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Option4ActionPerformed

    private void AnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnswerActionPerformed

    private void QuestionNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuestionNameActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
           String id = Id.getText();
           String name = QuestionName.getText();
           String opt1 = Option1.getText();
           String opt2 = Option2.getText();
           String opt3 = Option3.getText();
           String opt4 = Option4.getText();
           String ans = Answer.getText();
           try{
               Connection con= ConnectionProvider.getCon();
               PreparedStatement PS = con.prepareStatement("INSERT INTO Question VALUES(?,?,?,?,?,?,?,?)");
               PS.setInt(1,topicId);
               PS.setString(2,id);
               PS.setString(3,name);
               PS.setString(4,opt1);
               PS.setString(5,opt2);
               PS.setString(6,opt3);
               PS.setString(7,opt4);
               PS.setString(8,ans);
               PS.executeUpdate();
               JFrame jf= new JFrame();
               JOptionPane.showMessageDialog(jf,"Successfully Updated");
               setVisible(false);
               new addNewQuestion().setVisible(true);
           }
           catch(Exception e){
               JFrame jf = new JFrame();
               jf.setAlwaysOnTop(true);
               JOptionPane.showMessageDialog(jf,e);
           }
    }//GEN-LAST:event_saveActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        Id.setText("");
        QuestionName.setText("");
        Option1.setText("");
        Option2.setText("");
        Option3.setText("");
        Option4.setText("");
        Answer.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        adminHome.open=0;
        setVisible(false);
    }//GEN-LAST:event_CloseActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed

         try{
             Connection con=ConnectionProvider.getCon();
             Statement st = con.createStatement();
             ResultSet  rs = st.executeQuery("Select topicid from quiztopic where  Upper(topicname) ='" + topic + "'");
            if(rs.next()){
                TopicId.setText(rs.getInt(1)+""); 
            }
            else{
                JOptionPane.showMessageDialog(this,"this topic doesn't exist");
                int option = JOptionPane.showConfirmDialog(this,"Do you want to create New Quiz Topic ","select",JOptionPane.YES_NO_OPTION);
                  if(option == 0){
                      addNewTopic();
                      TopicId.setText(topicId+"");
                      JOptionPane.showMessageDialog(this,"new Topic added");
                  }
                  else{
                      TopicSearch.setText("Enter topic name");
                  }
            }
        }
        catch(Exception e){
            JFrame jf= new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf,e);
           
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void TopicSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TopicSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TopicSearchActionPerformed

    private void TopicSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TopicSearchFocusGained
        TopicSearch.setText("");
    }//GEN-LAST:event_TopicSearchFocusGained

    private void TopicSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TopicSearchFocusLost
        topic = TopicSearch.getText().toUpperCase();
         topic = topic.trim();
    }//GEN-LAST:event_TopicSearchFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addNewQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Answer;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Close;
    private javax.swing.JLabel Id;
    private javax.swing.JTextField Option1;
    private javax.swing.JTextField Option2;
    private javax.swing.JTextField Option3;
    private javax.swing.JTextField Option4;
    private javax.swing.JTextField QuestionName;
    private javax.swing.JButton Search;
    private javax.swing.JLabel TopicId;
    private javax.swing.JTextField TopicSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
