import javax.swing.JFrame;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bhadoriya
 */
public class adminHome extends javax.swing.JFrame {
   public static int open=0;
    /**
     * Creates new form adminHome
     */
    public adminHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ViewTopic = new javax.swing.JMenu();
        AddNewQuestion = new javax.swing.JMenu();
        UpdateQuestion = new javax.swing.JMenu();
        DeleteQuestion = new javax.swing.JMenu();
        AllQuestion = new javax.swing.JMenu();
        AllStudentResult = new javax.swing.JMenu();
        Logout = new javax.swing.JMenu();
        Exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, 1370, -1));

        jMenuBar1.setBackground(new java.awt.Color(0, 204, 204));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Navigation Bar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 204, 204))); // NOI18N
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        ViewTopic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all questions.png"))); // NOI18N
        ViewTopic.setText("View Topic");
        ViewTopic.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewTopic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewTopicMouseClicked(evt);
            }
        });
        jMenuBar1.add(ViewTopic);

        AddNewQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add new question.png"))); // NOI18N
        AddNewQuestion.setText("Add New Question");
        AddNewQuestion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddNewQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddNewQuestionMouseClicked(evt);
            }
        });
        jMenuBar1.add(AddNewQuestion);

        UpdateQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Update Question.png"))); // NOI18N
        UpdateQuestion.setText("Update Question");
        UpdateQuestion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateQuestionMouseClicked(evt);
            }
        });
        jMenuBar1.add(UpdateQuestion);

        DeleteQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete Question.png"))); // NOI18N
        DeleteQuestion.setText("Delete Qustion");
        DeleteQuestion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteQuestionMouseClicked(evt);
            }
        });
        jMenuBar1.add(DeleteQuestion);

        AllQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all questions.png"))); // NOI18N
        AllQuestion.setText("All Question");
        AllQuestion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AllQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllQuestionMouseClicked(evt);
            }
        });
        jMenuBar1.add(AllQuestion);

        AllStudentResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all student result.png"))); // NOI18N
        AllStudentResult.setText("All Student Result");
        AllStudentResult.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AllStudentResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllStudentResultMouseClicked(evt);
            }
        });
        jMenuBar1.add(AllStudentResult);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logout.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(Logout);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        Exit.setText("Exit");
        Exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jMenuBar1.add(Exit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
       JFrame jf = new JFrame();
       jf.setAlwaysOnTop(true);
       int a = JOptionPane.showConfirmDialog(jf,"Do you really want to Logout","Select",JOptionPane.YES_NO_OPTION);
       if(a == 0){
           setVisible(false);
           new loginAdmin().setVisible(true);  
       }
        
    }//GEN-LAST:event_LogoutMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
       JFrame jf = new JFrame();
       jf.setAlwaysOnTop(true);
       int a = JOptionPane.showConfirmDialog(jf,"Do you really want to Exit Application","Select",JOptionPane.YES_NO_OPTION);
       if(a == 0){
            System.exit(0);
       }
        
    }//GEN-LAST:event_ExitMouseClicked

    private void AddNewQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewQuestionMouseClicked
        if(open ==0){
            new addNewQuestion().setVisible(true);
            open=1;
        }else{
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"one form already Open");
        }
    }//GEN-LAST:event_AddNewQuestionMouseClicked

    private void UpdateQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateQuestionMouseClicked
        if(open ==0){
            new updateQuestion().setVisible(true);
            open=1;
        }else{
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"one form already Open");
        }
    }//GEN-LAST:event_UpdateQuestionMouseClicked

    private void AllQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllQuestionMouseClicked
        if(open ==0){
            new allQuestion().setVisible(true);
            open=1;
        }else{
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"one form already Open");
        }
    }//GEN-LAST:event_AllQuestionMouseClicked

    private void DeleteQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteQuestionMouseClicked
        if(open ==0){
            new deleteQuestion().setVisible(true);
            open=1;
        }else{
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"one form already Open");
        }
    }//GEN-LAST:event_DeleteQuestionMouseClicked

    private void ViewTopicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewTopicMouseClicked
         if(open ==0){
            new viewTopic().setVisible(true);
            open=1;
        }else{
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"one form already Open");
        }
    }//GEN-LAST:event_ViewTopicMouseClicked

    private void AllStudentResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllStudentResultMouseClicked
        if(open ==0){
            new allStudentResult().setVisible(true);
            open=1;
        }else{
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"one form already Open");
        }
    }//GEN-LAST:event_AllStudentResultMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AddNewQuestion;
    private javax.swing.JMenu AllQuestion;
    private javax.swing.JMenu AllStudentResult;
    private javax.swing.JMenu DeleteQuestion;
    private javax.swing.JMenu Exit;
    private javax.swing.JMenu Logout;
    private javax.swing.JMenu UpdateQuestion;
    private javax.swing.JMenu ViewTopic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
