import Project.ConnectionProvider;
import java.sql.*;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bhadoriya
 */
public class chooseTopic extends javax.swing.JFrame {
    int sId;
    String topic="";
    /**
     * Creates new form chooseTopic
     */
    public chooseTopic() {
        initComponents();
        
        
    }
    public chooseTopic(int id){
      initComponents();
        sId =id;
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
          ResultSet rs = st.executeQuery("select name from student where sid='"+sId+"'");
          if(rs.next()){
              StudentDetails.setText(rs.getString(1));
          }
        }
        catch(Exception e){}
      try{
          Connection con = ConnectionProvider.getCon();
          Statement st = con.createStatement();
          ResultSet rs = st.executeQuery("select *from quizTopic");
          Topic.removeAllItems();
          while(rs.next()){
               Topic.addItem(rs.getString(2));
          }
      } 
      catch(Exception e){
        JOptionPane.showMessageDialog(this,e);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        StudentDetails = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Start = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Topic = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(70, 130, 180));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Algerian", 1, 40)); // NOI18N
        jLabel4.setText("Quiz List");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 15, 257, -1));

        StudentDetails.setBackground(new java.awt.Color(255, 153, 0));
        StudentDetails.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        StudentDetails.setForeground(new java.awt.Color(255, 255, 255));
        StudentDetails.setText("Profile");
        StudentDetails.setBorder(null);
        StudentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(StudentDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, 270, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1360, 90));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("1. The Student may not use his or her textbook , course notes , receive help from a proctor or any other outside source.\n\n2. Student must complete the 10-question multiple-choice exam within the 10 minute time   frame alloted for the exam.\n\n3. Student must not stop the session and then return to it. This is especially   importantthe online environment where the system will \"time-out\" and not allow the student or you to reenter the exam .\n  \n   Number of Question:10\n   Exam Duration:10min\n   All The Very Best!");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 119, 1360, 286));

        Start.setBackground(new java.awt.Color(0, 204, 0));
        Start.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Start.setForeground(new java.awt.Color(255, 255, 255));
        Start.setText("Start Your Quiz");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        jPanel1.add(Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 558, 498, 55));

        Back.setBackground(new java.awt.Color(255, 102, 0));
        Back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 558, 496, 55));

        Topic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Topic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TopicActionPerformed(evt);
            }
        });
        jPanel1.add(Topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 454, 309, 34));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("     Choose Topic ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 173, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
         if(topic.equals("")){
             JOptionPane.showMessageDialog(this,"please Select any topic");
         }
         else{
             setVisible(false);
             new quizStudent(topic,sId).setVisible(true);
         }
    }//GEN-LAST:event_StartActionPerformed

    private void TopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TopicActionPerformed
        topic = (String)Topic.getSelectedItem();
    }//GEN-LAST:event_TopicActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
          setVisible(false);
          new index().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void StudentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentDetailsActionPerformed
         setVisible(false);
         new studentProfile(sId).setVisible(true);
    }//GEN-LAST:event_StudentDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chooseTopic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chooseTopic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chooseTopic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chooseTopic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chooseTopic(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Start;
    private javax.swing.JButton StudentDetails;
    private javax.swing.JComboBox<String> Topic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}

