import java.sql.*;
import Project.ConnectionProvider;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.awt.Color;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bhadoriya
 */
public class studentDetails extends javax.swing.JFrame {
   Boolean checkEmail=false;
   Boolean checkName =false;
   Boolean checkContact = false;
   Boolean checkPassword = false;
   int sId= 1;
   String name="";
   String email="";
   String contact="";
   String password="";
   
    /**
     * Creates new form studentDetails
     */
    public studentDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        ContactNum = new javax.swing.JTextField();
        SignUp = new javax.swing.JButton();
        EmailWarning = new javax.swing.JLabel();
        emailWarning = new javax.swing.JLabel();
        ContactWarning = new javax.swing.JLabel();
        NameWarning = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LogIn = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CreatePassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ConfirmPassword = new javax.swing.JPasswordField();
        PasswordWarning = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Sign up ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 90, 50));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 24, 37, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 40, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 180, 37, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 40, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Contact Number");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 110, -1));

        Name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Name.setForeground(new java.awt.Color(204, 204, 204));
        Name.setText("full name");
        Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameFocusLost(evt);
            }
        });
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 310, -1));

        Email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Email.setForeground(new java.awt.Color(204, 204, 204));
        Email.setText("Email-address");
        Email.setAutoscrolls(false);
        Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailFocusLost(evt);
            }
        });
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 310, -1));

        ContactNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ContactNum.setForeground(new java.awt.Color(204, 204, 204));
        ContactNum.setText("Mobile Number");
        ContactNum.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ContactNum.setPreferredSize(new java.awt.Dimension(100, 21));
        ContactNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ContactNumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ContactNumFocusLost(evt);
            }
        });
        ContactNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumActionPerformed(evt);
            }
        });
        getContentPane().add(ContactNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 310, 30));

        SignUp.setBackground(new java.awt.Color(0, 0, 204));
        SignUp.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SignUp.setForeground(new java.awt.Color(255, 255, 255));
        SignUp.setText("Sign up");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        getContentPane().add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 310, 30));

        EmailWarning.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailWarningFocusGained(evt);
            }
        });
        getContentPane().add(EmailWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 330, -1));

        emailWarning.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailWarning.setForeground(new java.awt.Color(255, 0, 0));
        emailWarning.setText("    ");
        getContentPane().add(emailWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 310, -1));

        ContactWarning.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ContactWarning.setForeground(new java.awt.Color(255, 0, 51));
        ContactWarning.setText("     ");
        getContentPane().add(ContactWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 310, -1));

        NameWarning.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NameWarning.setForeground(new java.awt.Color(255, 0, 0));
        NameWarning.setText("  ");
        getContentPane().add(NameWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 225, 310, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("*");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("*");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 10, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("*");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 20, -1));

        LogIn.setBackground(new java.awt.Color(0, 204, 0));
        LogIn.setForeground(new java.awt.Color(255, 255, 255));
        LogIn.setText("Log in");
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });
        getContentPane().add(LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, 157, -1));

        Back.setBackground(new java.awt.Color(153, 153, 153));
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 147, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Create Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 20, 10));

        CreatePassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CreatePasswordFocusLost(evt);
            }
        });
        CreatePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(CreatePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 310, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Confirm Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("*");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 20, -1));

        ConfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ConfirmPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ConfirmPasswordFocusLost(evt);
            }
        });
        getContentPane().add(ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 310, -1));

        PasswordWarning.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PasswordWarning.setForeground(new java.awt.Color(255, 0, 0));
        PasswordWarning.setText("  ");
        getContentPane().add(PasswordWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 310, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContactNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumActionPerformed
        
    }//GEN-LAST:event_ContactNumActionPerformed

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        if( !(checkName && checkEmail && checkContact && checkPassword)){
            JOptionPane.showMessageDialog(this, "Incorrect Email or Password");
        }
        else{
        try{
            Connection con = ConnectionProvider.getCon();
            Statement p = con.createStatement();
            
            // result set for generating new student Id
            ResultSet r = p.executeQuery("Select count(*) from Student ");
            if(r.next())
               sId = r.getInt(1)+1;
            
            // checking student already Enrolled or not
            ResultSet rs = p.executeQuery("Select * from Student where email='"+email+"'");
            if(rs.next()){
                JOptionPane.showMessageDialog(this,"this Student is already enrolled");
            }
            else{
                // adding new student into table
                PreparedStatement ps = con.prepareStatement("Insert into student values(?,?,?,?,?)");
                ps.setInt(1, sId);
                ps.setString(2, name);
                ps.setString(3, email);
                ps.setLong(4, Long.parseLong(contact));
                ps.setString(5, password);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this,"student registered Succesfully");
                setVisible(false);
                new chooseTopic(sId).setVisible(true);
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
        }
    }//GEN-LAST:event_SignUpActionPerformed

    private void EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFocusLost
        email =Email.getText().trim();
        if( email.equals("")){
           emailWarning.setText("required ");
           Email.setText("Email-address");
           Email.setForeground(new Color(204,204,204));
       }
       else if(!email.endsWith("@gmail.com")){
           emailWarning.setText("Invalid EmailId ");
       }
       else
           checkEmail=true;
    }//GEN-LAST:event_EmailFocusLost

    private void EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFocusGained
        Email.setForeground(new Color(0,0,0));
        emailWarning.setText("");
        if(Email.getText().equals("Email-address")){
            Email.setText("");
        }
            
    }//GEN-LAST:event_EmailFocusGained

    private void EmailWarningFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailWarningFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailWarningFocusGained

    private void ContactNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContactNumFocusGained
        ContactNum.setForeground(new Color(0,0,0));
        ContactWarning.setText("");
        if(ContactNum.getText().equals("Mobile Number")){
            ContactNum.setText("");
        }      
    }//GEN-LAST:event_ContactNumFocusGained

    private void ContactNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContactNumFocusLost
        contact = ContactNum.getText().trim();
        if( contact.equals("")){
           ContactWarning.setText("required ");
           ContactNum.setText("Mobile Number");
           ContactNum.setForeground(new Color(204,204,204));
       }
       else if(contact.length() != 10){
            ContactWarning.setText("Invalid Contact Number");
        }else{
            checkContact=true;
            for(char ch:contact.toCharArray()){
                if(!Character.isDigit(ch)){
                    ContactWarning.setText("Invalid Contact Number");
                    checkContact = false;
                    break;
                }
            }
        }
    }//GEN-LAST:event_ContactNumFocusLost

    private void NameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameFocusGained
       Name.setForeground(new Color(0,0,0));
        NameWarning.setText("");
        if(Name.getText().equals("full name")){
            Name.setText("");
        }
    }//GEN-LAST:event_NameFocusGained

    private void NameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameFocusLost
        name=Name.getText().trim();
        if( name.equals("")){
           Name.setText("full name");
           Name.setForeground(new Color(204,204,204));
           NameWarning.setText("required ");
       }
       else
            checkName=true;
    }//GEN-LAST:event_NameFocusLost

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
          setVisible(false);
          new loginStudent().setVisible(true);
    }//GEN-LAST:event_LogInActionPerformed

    private void CreatePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePasswordActionPerformed
         
    }//GEN-LAST:event_CreatePasswordActionPerformed

    private void CreatePasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CreatePasswordFocusLost
          password = new String(CreatePassword.getPassword());
    }//GEN-LAST:event_CreatePasswordFocusLost

    private void ConfirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmPasswordFocusLost
          String confirmPassword = new String(ConfirmPassword.getPassword());
        if(confirmPassword.equals(password)){
            checkPassword =true;
        }
        else{
            PasswordWarning.setText("Please re-enter your password");
        }
    }//GEN-LAST:event_ConfirmPasswordFocusLost

    private void ConfirmPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmPasswordFocusGained
        PasswordWarning.setText("");
        if(PasswordWarning.getText().equals("")){
            ConfirmPassword.setText("");
        }
    }//GEN-LAST:event_ConfirmPasswordFocusGained

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
          setVisible(false);
          new index().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JTextField ContactNum;
    private javax.swing.JLabel ContactWarning;
    private javax.swing.JPasswordField CreatePassword;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel EmailWarning;
    private javax.swing.JButton LogIn;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel NameWarning;
    private javax.swing.JLabel PasswordWarning;
    private javax.swing.JButton SignUp;
    private javax.swing.JLabel emailWarning;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
